### ISSUE TITLE
[Feature]希望能开放设置padding

### ISSUE THREAD

**Issue by XiFengLang** [herowws/flutter_popup#2]
如图外围的白色区域，希望能开放控制

**Comment by XiFengLang** [comment]
![Uploading 20231212152456.jpg…]()

**Comment by XiFengLang** [comment]
```C
CustomPopup(
                  content: Column(
                    mainAxisSize: MainAxisSize.min,
                    children: ["12", "23", "24"].map((e) {
                      return Container(
                        color: Colors.red,
                        width: 100,
                        height: 36,
                        child: TextButton(
                          style: ButtonStyle(
                            alignment: Alignment.centerLeft,
                          ),
                          child: Text(
                            e,
                            style: FontStyle.assist()
                                .toTextStyle(color: ColorName.aiColorM10),
                          ),
                          onPressed: () {
                            Navigator.of(context).pop();
                          },
                        ),
                      );
                    }).toList(),
                  ),
                  child: MySelector(content: "12", width: 100, height: 32),
                )
```

**Comment by herowws** [comment]
> 如图外围的白色区域，希望能开放控制

提供的图片已缺失

**Comment by herowws** [comment]
> CustomPopup(
>                   content: Column(
>                     mainAxisSize: MainAxisSize.min,
>                     children: ["12", "23", "24"].map((e) {
>                       return Container(
>                         color: Colors.red,
>                         width: 100,
>                         height: 36,
>                         child: TextButton(
>                           style: ButtonStyle(
>                             alignment: Alignment.centerLeft,
>                           ),
>                           child: Text(
>                             e,
>                             style: FontStyle.assist()
>                                 .toTextStyle(color: ColorName.aiColorM10),
>                           ),
>                           onPressed: () {
>                             Navigator.of(context).pop();
>                           },
>                         ),
>                       );
>                     }).toList(),
>                   ),
>                   child: MySelector(content: "12", width: 100, height: 32),
>                 )

update flutter_popup version
